### ISSUE TITLE
Probably doing something quite wrong... :-)

### ISSUE THREAD

**Issue by ddebernardy** [umitanuki/kmeans-postgresql#2]
This one compiled great, however your makefiles seem to want me to be in some special location.

```
DB:~/pgdevel/kmeans-postgresql $ sudo make installcheck USE_PGXS=1 PGUSER=postgres
/opt/local/lib/postgresql91/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=. --psqldir=/opt/local/lib/postgresql91/bin   --dbname=contrib_regression kmeans
(using postmaster on Unix socket, default port)
pg_regress: could not open file "sql/kmeans.sql" for writing: No such file or directory
make: *** [installcheck] Error 2
DB:~/pgdevel/kmeans-postgresql $ sudo make installcheck PGUSER=postgres
Makefile:34: ../../src/Makefile.global: No such file or directory
Makefile:35: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.
```

Terribly sorry if this may sound trivial to you. I take it I need to do this stuff from the postgres/contrib folder. Or might I have missed exporting something or adding an extra parameter somewhere?

**Comment by umitanuki** [comment]
As the message tells, you need write permission on the current directory for mkdir "sql". "sql/kmeans.sql" will be created from "input/kmeans.source"

**Comment by ddebernardy** [comment]
I would have thought that sudo would catch it... C is really rusty.

Another issue is I hadn't run make install before installcheck... Thanks for your time!

**Comment by umitanuki** [comment]
> I would have thought that sudo would catch it... C is really rusty.

It's not C. It's make :)
